'use strict';

module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            'Items',
            [
                {
                    item_id: 1,
                    package_id: 1,
                    item_name: 'Pizza',
                    peanut_preferences: true,
                    dairy_preferences: false,
                    fish_preferences: false,
                    egg_preferences: false,
                    best_before_date: new Date('December 3, 2022 03:00:00'),
                    quantity: 2,
                    perishable_status: true,
                    weight: 0.4,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 2,
                    package_id: 1,
                    item_name: 'Pasta',
                    peanut_preferences: true,
                    dairy_preferences: false,
                    fish_preferences: true,
                    egg_preferences: false,
                    best_before_date: new Date('December 3, 2022 03:00:00'),
                    quantity: 1,
                    perishable_status: true,
                    weight: 0.2,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 3,
                    package_id: 2,
                    item_name: 'Salad',
                    peanut_preferences: false,
                    dairy_preferences: false,
                    fish_preferences: false,
                    egg_preferences: true,
                    best_before_date: new Date('December 7, 2022 03:00:00'),
                    quantity: 2,
                    perishable_status: true,
                    weight: 0.4,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 4,
                    package_id: 3,
                    item_name: 'Soup',
                    peanut_preferences: false,
                    dairy_preferences: true,
                    fish_preferences: false,
                    egg_preferences: false,
                    best_before_date: new Date('December 1, 2022 03:00:00'),
                    quantity: 5,
                    perishable_status: true,
                    weight: 0.5,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 5,
                    package_id: 4,
                    item_name: 'Tacos',
                    peanut_preferences: false,
                    dairy_preferences: false,
                    fish_preferences: true,
                    egg_preferences: false,
                    best_before_date: new Date('December 4, 2022 03:00:00'),
                    quantity: 10,
                    perishable_status: true,
                    weight: 1,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 6,
                    package_id: 5,
                    item_name: 'Pizza',
                    peanut_preferences: false,
                    dairy_preferences: false,
                    fish_preferences: false,
                    egg_preferences: true,
                    best_before_date: new Date('December 3, 2022 03:00:00'),
                    quantity: 2,
                    perishable_status: true,
                    weight: 0.4,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 7,
                    package_id: 5,
                    item_name: 'Hoome food',
                    peanut_preferences: false,
                    dairy_preferences: false,
                    fish_preferences: false,
                    egg_preferences: false,
                    best_before_date: new Date('December 3, 2022 03:00:00'),
                    quantity: 2,
                    perishable_status: true,
                    weight: 0.4,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    item_id: 8,
                    package_id: 5,
                    item_name: 'Home food',
                    peanut_preferences: false,
                    dairy_preferences: false,
                    fish_preferences: false,
                    egg_preferences: true,
                    best_before_date: new Date('December 3, 2022 03:00:00'),
                    quantity: 2,
                    perishable_status: true,
                    weight: 0.4,
                    weight_units: 'kg',
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },

            ],
            {}
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Items', null, {});
    },
};
